
ad_p1_sp1_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '开店,创业,北京, 旅游,机票,MP3'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp1_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=121' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp1_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=122' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp1_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=123' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp1_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=216' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp1_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp1_n7 = "";
ad_p1_sp1_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp2_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp2_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=124' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp2_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=125' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp2_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=126' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp2_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=217' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp2_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp2_n7 = "";
ad_p1_sp2_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp3_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp3_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=127' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp3_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=128' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp3_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=129' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp3_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=218' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp3_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp3_n7 = "";
ad_p1_sp3_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp4_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp4_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=130' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp4_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=131' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp4_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=132' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp4_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=219' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp4_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp4_n7 = "";
ad_p1_sp4_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp5_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp5_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=133' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp5_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=134' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp5_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=135' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp5_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=220' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp5_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp5_n7 = "";
ad_p1_sp5_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp6_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp6_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=136' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp6_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=137' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp6_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=138' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp6_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=221' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp6_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp6_n7 = "";
ad_p1_sp6_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp7_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp7_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=139' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp7_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=140' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp7_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=141' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp7_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=222' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp7_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp7_n7 = "";
ad_p1_sp7_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp8_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp8_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=142' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp8_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=143' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp8_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=144' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp8_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=223' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp8_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp8_n7 = "";
ad_p1_sp8_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp9_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp9_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=145' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp9_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=146' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp9_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=147' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp9_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=224' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp9_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp9_n7 = "";
ad_p1_sp9_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp10_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp10_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=148' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp10_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=149' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp10_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=150' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp10_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=225' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp10_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp10_n7 = "";
ad_p1_sp10_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp11_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp11_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=151' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp11_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=152' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp11_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=153' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp11_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=226' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp11_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp11_n7 = "";
ad_p1_sp11_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp12_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp12_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=154' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp12_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=155' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp12_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=156' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp12_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=227' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp12_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp12_n7 = "";
ad_p1_sp12_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp13_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp13_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=157' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp13_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=158' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp13_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=159' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp13_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=228' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp13_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp13_n7 = "";
ad_p1_sp13_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp14_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp14_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=160' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp14_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=161' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp14_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=162' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp14_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=229' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp14_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp14_n7 = "";
ad_p1_sp14_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp15_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp15_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=163' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp15_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=164' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp15_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=165' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp15_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=230' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp15_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp15_n7 = "";
ad_p1_sp15_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp16_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp16_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=166' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp16_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=167' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp16_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=168' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp16_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=231' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp16_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp16_n7 = "";
ad_p1_sp16_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp17_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp17_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=169' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp17_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=170' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp17_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=171' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp17_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=232' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp17_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp17_n7 = "";
ad_p1_sp17_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp18_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp18_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=172' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp18_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=173' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp18_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=174' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp18_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=233' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp18_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp18_n7 = "";
ad_p1_sp18_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp19_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp19_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=175' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp19_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=176' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp19_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=177' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp19_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=234' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp19_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp19_n7 = "";
ad_p1_sp19_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
ad_p1_sp20_n1 = "<script type='text/javascript'> google_ad_client = 'pub-3722904002665960'; google_ad_width = 468; google_ad_height = 60; google_hints = '加盟,交友,赚钱,出国,股票,数码,电影'; google_language = 'zh-CN'; google_ad_format = '468x60_as'; google_ad_type = 'text_image'; google_ad_channel =''; google_color_border = 'FFFFFF'; google_color_bg = 'FFFFFF'; google_color_link = '0066CC'; google_color_text = '0066CC'; google_color_url = '0066CC'; </script> <script type='text/javascript'   src='http://pagead2.googlesyndication.com/pagead/show_ads.js'></script>";
ad_p1_sp20_n2 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=178' target='_blank'>电话购买乐趣币</a>";
ad_p1_sp20_n3 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=179' target='_blank'>民族英雄出征北极</a>";
ad_p1_sp20_n4 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=180' target='_blank'>诗人评选结果出炉</a>";
ad_p1_sp20_n5 = "<a href='http://ad.netsh.com/count_advert.php?p_iAdvertID=235' target='_blank'><img src='http://xz.netsh.com/image/cfutong.gif' width='234' height='60' border='0'></a>";
ad_p1_sp20_n6 = "<script>var YahooCNADConfig=new Array();YahooCNADConfig['adid']=921;YahooCNADConfig['wid']=32807;YahooCNADConfig['w']=760;YahooCNADConfig['h']=90;</script><script type='text/javascript' src='http://view.aliunion.cn.yahoo.com/showad.php'></script>";
ad_p1_sp20_n7 = "";
ad_p1_sp20_n8 = "<script src='http://ad.netsh.com/20070621_allyes/other_article.js'></script>";
